language: python
python:
#  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

install:
  - pip install .

script:
  - python tests/sample.py
  - python tests/integration_test/test_logtail_config.py
  - python tests/sample_consumer.py
